parent: tv_electronic_electron_1_7_v1
name: childtheme
display_name: My first child Theme
version: 1.0.0
assets:
  use_parent_assets: true
  js:
    all:
      - id: theme-custom
        path: assets/js/custom.js
        priority: 1000
        position: bottom